import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Link Pilot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          position="top-right"
          reverseOrder={false}
          gutter={8}
          toastOptions={{
            className: "",
            duration: 5000,
            removeDelay: 1000,

            style: {
              background: "#0a0a0a",
              color: "#ffffff",
              border: "1px solid rgba(255,255,255,0.08)",
              borderRadius: "16px",
              padding: "14px 16px",
              boxShadow: "0 10px 30px rgba(0,0,0,0.45)",
            },

            success: {
              duration: 3000,
              style: {
                background: "#0a0a0a",
                color: "#ffffff",
                border: "1px solid rgba(34,197,94,0.35)",
              },
              iconTheme: {
                primary: "#22c55e",
                secondary: "#0a0a0a",
              },
            },

            error: {
              style: {
                background: "#0a0a0a",
                color: "#ffffff",
                border: "1px solid rgba(239,68,68,0.35)",
              },
              iconTheme: {
                primary: "#ef4444",
                secondary: "#0a0a0a",
              },
            },

            loading: {
              style: {
                background: "#0a0a0a",
                color: "#ffffff",
                border: "1px solid rgba(255,255,255,0.08)",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
